version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
      DIRECT_URL: postgres://postgres:password@db:5432/mydb
    restart: always
    command: >
      sh -c "npx prisma migrate deploy && node dist/main"  # Executa migrações antes de iniciar

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
