version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/mydb
    restart: always
    command: >
      sh -c "npx prisma migrate deploy && node dist/main"  # Executa migrações antes de iniciar

  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
